
export const LIMITS = {

  MAX_REQUESTS_PER_MINUTE: 60,

  MAX_CONCURRENT_PR_PROCESSING: 5,

  MAX_MEMORY_MB: 512,

  MAX_EVENT_LOOP_DELAY_MS: 200,

  MAX_DECISION_RECORDS_IN_MEMORY: 1000,
} as const;